name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Merge Split Zip Files
      run: |
        cat my_project.zip.part_* > full_project.zip
        unzip -q full_project.zip
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Grant execute permission for gradlew
      run: chmod +x YR\ POSTRENDER/gradlew
    - name: Build with Gradle
      run: cd YR\ POSTRENDER && ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: YR\ POSTRENDER/app/build/outputs/apk/debug/*.apk
        
